-- MySQL Script generated by MySQL Workbench
-- Wed Jun  4 12:47:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema eoxsense
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eoxsense
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eoxsense` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `eoxsense` ;

-- -----------------------------------------------------
-- Table `eoxsense`.`experiments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eoxsense`.`experiments` (
  `id_experiment` VARCHAR(45) NOT NULL,
  `comments_experiment` TEXT NULL DEFAULT NULL,
  `number_of_channels` INT NULL DEFAULT NULL,
  `fisiological_parameter` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_experiment`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eoxsense`.`calibration_glucose`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eoxsense`.`calibration_glucose` (
  `avoid_duplicates` INT NOT NULL,
  `ID_experiment` VARCHAR(45) NOT NULL,
  `ID_channel` VARCHAR(10) NOT NULL,
  `raw/corrected` VARCHAR(10) NOT NULL,
  `blank/no` VARCHAR(45) NULL DEFAULT NULL,
  `sensitivity` FLOAT NULL DEFAULT NULL,
  `R2` FLOAT NULL DEFAULT NULL,
  `slope` FLOAT NULL DEFAULT NULL,
  `intercept` FLOAT NULL DEFAULT NULL,
  `sensitivity_mM` FLOAT NULL DEFAULT NULL,
  `R2_mM` FLOAT NULL DEFAULT NULL,
  `slope_mM` FLOAT NULL DEFAULT NULL,
  `intercept_mM` FLOAT NULL DEFAULT NULL,
  `EMF_sample1` FLOAT NULL DEFAULT NULL,
  `EMF_sample2` FLOAT NULL DEFAULT NULL,
  `EMF_sample3` FLOAT NULL DEFAULT NULL,
  `EMF_sample4` FLOAT NULL DEFAULT NULL,
  `EMF_sample5` FLOAT NULL DEFAULT NULL,
  `EMF_sample6` FLOAT NULL DEFAULT NULL,
  `EMF_sample7` FLOAT NULL DEFAULT NULL,
  `EMF_sample8` FLOAT NULL DEFAULT NULL,
  `Glucose_sample1` FLOAT NULL DEFAULT NULL,
  `Glucose_sample2` FLOAT NULL DEFAULT NULL,
  `Glucose_sample3` FLOAT NULL DEFAULT NULL,
  `Glucose_sample4` FLOAT NULL DEFAULT NULL,
  `Glucose_sample5` FLOAT NULL DEFAULT NULL,
  `Glucose_sample6` FLOAT NULL DEFAULT NULL,
  `Glucose_sample7` FLOAT NULL DEFAULT NULL,
  `Glucose_sample8` FLOAT NULL DEFAULT NULL,
  `Glucose_sample1_mM` FLOAT NULL DEFAULT NULL,
  `Glucose_sample2_mM` FLOAT NULL DEFAULT NULL,
  `Glucose_sample3_mM` FLOAT NULL DEFAULT NULL,
  `Glucose_sample4_mM` FLOAT NULL DEFAULT NULL,
  `Glucose_sample5_mM` FLOAT NULL DEFAULT NULL,
  `Glucose_sample6_mM` FLOAT NULL DEFAULT NULL,
  `Glucose_sample7_mM` FLOAT NULL DEFAULT NULL,
  `Glucose_sample8_mM` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`avoid_duplicates`),
  UNIQUE INDEX `evitar_duplicados_UNIQUE` (`avoid_duplicates` ASC) VISIBLE,
  INDEX `id_exp_idx` (`ID_experiment` ASC) VISIBLE,
  CONSTRAINT `id_exp`
    FOREIGN KEY (`ID_experiment`)
    REFERENCES `eoxsense`.`experiments` (`id_experiment`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eoxsense`.`calibration_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eoxsense`.`calibration_values` (
  `avoid_duplicates` INT NOT NULL,
  `ID_experiment` VARCHAR(45) NOT NULL,
  `raw/corrected` VARCHAR(10) NOT NULL,
  `LogH2O2` FLOAT NULL DEFAULT NULL,
  `H2O2mM` FLOAT NULL DEFAULT NULL,
  `Chn_1_mV` FLOAT NULL DEFAULT NULL,
  `Chn_2_mV` FLOAT NULL DEFAULT NULL,
  `Chn_3_mV` FLOAT NULL DEFAULT NULL,
  `Chn_4_mV` FLOAT NULL DEFAULT NULL,
  `Chn_5_mV` FLOAT NULL DEFAULT NULL,
  `Chn_6_mV` FLOAT NULL DEFAULT NULL,
  `Chn_7_mV` FLOAT NULL DEFAULT NULL,
  `Chn_8_mV` FLOAT NULL DEFAULT NULL,
  `Chn_9` FLOAT NULL DEFAULT NULL,
  `Chn_10` FLOAT NULL DEFAULT NULL,
  `Chn_11` FLOAT NULL DEFAULT NULL,
  `Chn_12` FLOAT NULL DEFAULT NULL,
  `Chn_13` FLOAT NULL DEFAULT NULL,
  `Chn_14` FLOAT NULL DEFAULT NULL,
  `Chn_15` FLOAT NULL DEFAULT NULL,
  `Chn_16` FLOAT NULL DEFAULT NULL,
  `Chn_17` FLOAT NULL DEFAULT NULL,
  `Chn_18` FLOAT NULL DEFAULT NULL,
  `Chn_19` FLOAT NULL DEFAULT NULL,
  `Chn_20` FLOAT NULL DEFAULT NULL,
  `Chn_21` FLOAT NULL DEFAULT NULL,
  `Chn_22` FLOAT NULL DEFAULT NULL,
  `Chn_23` FLOAT NULL DEFAULT NULL,
  `Chn_24` FLOAT NULL DEFAULT NULL,
  `Chn_25` FLOAT NULL DEFAULT NULL,
  `Chn_26` FLOAT NULL DEFAULT NULL,
  `Chn_27` FLOAT NULL DEFAULT NULL,
  `Chn_28` FLOAT NULL DEFAULT NULL,
  `Chn_29` FLOAT NULL DEFAULT NULL,
  `Chn_30` FLOAT NULL DEFAULT NULL,
  `Chn_31` FLOAT NULL DEFAULT NULL,
  `Chn_32` FLOAT NULL DEFAULT NULL,
  `Chn_33` FLOAT NULL DEFAULT NULL,
  `Chn_34` FLOAT NULL DEFAULT NULL,
  `Chn_35` FLOAT NULL DEFAULT NULL,
  `Chn_36` FLOAT NULL DEFAULT NULL,
  `Chn_37` FLOAT NULL DEFAULT NULL,
  `Chn_38` FLOAT NULL DEFAULT NULL,
  `Chn_39` FLOAT NULL DEFAULT NULL,
  `Chn_40` FLOAT NULL DEFAULT NULL,
  `Chn_41` FLOAT NULL DEFAULT NULL,
  `Chn_42` FLOAT NULL DEFAULT NULL,
  `Chn_43` FLOAT NULL DEFAULT NULL,
  `Chn_44` FLOAT NULL DEFAULT NULL,
  `Chn_45` FLOAT NULL DEFAULT NULL,
  `Chn_46` FLOAT NULL DEFAULT NULL,
  `Chn_47` FLOAT NULL DEFAULT NULL,
  `Chn_48` FLOAT NULL DEFAULT NULL,
  `Chn_49` FLOAT NULL DEFAULT NULL,
  `Chn_50` FLOAT NULL DEFAULT NULL,
  `Average` FLOAT NULL DEFAULT NULL,
  `SD` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`avoid_duplicates`),
  UNIQUE INDEX `evitar_duplicados_UNIQUE` (`avoid_duplicates` ASC) VISIBLE,
  INDEX `id_exp_idx` (`ID_experiment` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`ID_experiment`)
    REFERENCES `eoxsense`.`experiments` (`id_experiment`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eoxsense`.`modelo_predictivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eoxsense`.`modelo_predictivo` (
  `avoid_duplicates` INT NOT NULL,
  `ID_experiment` VARCHAR(45) NOT NULL,
  `ID_muestras` TEXT NULL DEFAULT NULL,
  `activity` TEXT NULL DEFAULT NULL,
  `technique` TEXT NULL DEFAULT NULL,
  `W.E` TEXT NULL DEFAULT NULL,
  `sweat_ph` FLOAT NULL DEFAULT NULL,
  `num_channels` INT NULL DEFAULT NULL,
  `glucosa` FLOAT NULL DEFAULT NULL,
  `standard_deviation` FLOAT NULL DEFAULT NULL,
  `SD_percentage` FLOAT NULL DEFAULT NULL,
  `blood_glucose` FLOAT NULL DEFAULT NULL,
  `valid` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`avoid_duplicates`),
  INDEX `id_idx` (`ID_experiment` ASC) VISIBLE,
  CONSTRAINT `idd`
    FOREIGN KEY (`ID_experiment`)
    REFERENCES `eoxsense`.`experiments` (`id_experiment`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eoxsense`.`validation_glucose`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eoxsense`.`validation_glucose` (
  `avoid_duplicates` INT NOT NULL,
  `ID_experiment` VARCHAR(45) NOT NULL,
  `ID_channel` VARCHAR(10) NOT NULL,
  `raw/corrected` VARCHAR(10) NOT NULL,
  `blank/no` VARCHAR(45) NULL DEFAULT NULL,
  `sensitivity` FLOAT NULL DEFAULT NULL,
  `R2` FLOAT NULL DEFAULT NULL,
  `slope` FLOAT NULL DEFAULT NULL,
  `intercept` FLOAT NULL DEFAULT NULL,
  `sensitivity_mM` FLOAT NULL DEFAULT NULL,
  `R2_mM` FLOAT NULL DEFAULT NULL,
  `slope_mM` FLOAT NULL DEFAULT NULL,
  `intercept_mM` FLOAT NULL DEFAULT NULL,
  `EMF_sample1` FLOAT NULL DEFAULT NULL,
  `EMF_sample2` FLOAT NULL DEFAULT NULL,
  `EMF_sample3` FLOAT NULL DEFAULT NULL,
  `EMF_sample4` FLOAT NULL DEFAULT NULL,
  `EMF_sample5` FLOAT NULL DEFAULT NULL,
  `EMF_sample6` FLOAT NULL DEFAULT NULL,
  `EMF_sample7` FLOAT NULL DEFAULT NULL,
  `EMF_sample8` FLOAT NULL DEFAULT NULL,
  `Glucose_sample1` FLOAT NULL DEFAULT NULL,
  `Glucose_sample2` FLOAT NULL DEFAULT NULL,
  `Glucose_sample3` FLOAT NULL DEFAULT NULL,
  `Glucose_sample4` FLOAT NULL DEFAULT NULL,
  `Glucose_sample5` FLOAT NULL DEFAULT NULL,
  `Glucose_sample6` FLOAT NULL DEFAULT NULL,
  `Glucose_sample7` FLOAT NULL DEFAULT NULL,
  `Glucose_sample8` FLOAT NULL DEFAULT NULL,
  `Glucose_sample1_mM` FLOAT NULL DEFAULT NULL,
  `Glucose_sample2_mM` FLOAT NULL DEFAULT NULL,
  `Glucose_sample3_mM` FLOAT NULL DEFAULT NULL,
  `Glucose_sample4_mM` FLOAT NULL DEFAULT NULL,
  `Glucose_sample5_mM` FLOAT NULL DEFAULT NULL,
  `Glucose_sample6_mM` FLOAT NULL DEFAULT NULL,
  `Glucose_sample7_mM` FLOAT NULL DEFAULT NULL,
  `Glucose_sample8_mM` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`avoid_duplicates`),
  UNIQUE INDEX `evitar_duplicados_UNIQUE` (`avoid_duplicates` ASC) VISIBLE,
  INDEX `id_idx` (`ID_experiment` ASC) VISIBLE,
  CONSTRAINT `id_val`
    FOREIGN KEY (`ID_experiment`)
    REFERENCES `eoxsense`.`experiments` (`id_experiment`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eoxsense`.`validation_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eoxsense`.`validation_values` (
  `avoid_duplicates` INT NOT NULL,
  `ID_experiment` VARCHAR(45) NOT NULL,
  `raw/corrected` VARCHAR(10) NOT NULL,
  `LogH2O2` FLOAT NULL DEFAULT NULL,
  `H2O2mM` FLOAT NULL DEFAULT NULL,
  `Chn_1_mV` FLOAT NULL DEFAULT NULL,
  `Chn_2_mV` FLOAT NULL DEFAULT NULL,
  `Chn_3_mV` FLOAT NULL DEFAULT NULL,
  `Chn_4_mV` FLOAT NULL DEFAULT NULL,
  `Chn_5_mV` FLOAT NULL DEFAULT NULL,
  `Chn_6_mV` FLOAT NULL DEFAULT NULL,
  `Chn_7_mV` FLOAT NULL DEFAULT NULL,
  `Chn_8_mV` FLOAT NULL DEFAULT NULL,
  `Chn_9` FLOAT NULL DEFAULT NULL,
  `Chn_10` FLOAT NULL DEFAULT NULL,
  `Chn_11` FLOAT NULL DEFAULT NULL,
  `Chn_12` FLOAT NULL DEFAULT NULL,
  `Chn_13` FLOAT NULL DEFAULT NULL,
  `Chn_14` FLOAT NULL DEFAULT NULL,
  `Chn_15` FLOAT NULL DEFAULT NULL,
  `Chn_16` FLOAT NULL DEFAULT NULL,
  `Chn_17` FLOAT NULL DEFAULT NULL,
  `Chn_18` FLOAT NULL DEFAULT NULL,
  `Chn_19` FLOAT NULL DEFAULT NULL,
  `Chn_20` FLOAT NULL DEFAULT NULL,
  `Chn_21` FLOAT NULL DEFAULT NULL,
  `Chn_22` FLOAT NULL DEFAULT NULL,
  `Chn_23` FLOAT NULL DEFAULT NULL,
  `Chn_24` FLOAT NULL DEFAULT NULL,
  `Chn_25` FLOAT NULL DEFAULT NULL,
  `Chn_26` FLOAT NULL DEFAULT NULL,
  `Chn_27` FLOAT NULL DEFAULT NULL,
  `Chn_28` FLOAT NULL DEFAULT NULL,
  `Chn_29` FLOAT NULL DEFAULT NULL,
  `Chn_30` FLOAT NULL DEFAULT NULL,
  `Chn_31` FLOAT NULL DEFAULT NULL,
  `Chn_32` FLOAT NULL DEFAULT NULL,
  `Chn_33` FLOAT NULL DEFAULT NULL,
  `Chn_34` FLOAT NULL DEFAULT NULL,
  `Chn_35` FLOAT NULL DEFAULT NULL,
  `Chn_36` FLOAT NULL DEFAULT NULL,
  `Chn_37` FLOAT NULL DEFAULT NULL,
  `Chn_38` FLOAT NULL DEFAULT NULL,
  `Chn_39` FLOAT NULL DEFAULT NULL,
  `Chn_40` FLOAT NULL DEFAULT NULL,
  `Chn_41` FLOAT NULL DEFAULT NULL,
  `Chn_42` FLOAT NULL DEFAULT NULL,
  `Chn_43` FLOAT NULL DEFAULT NULL,
  `Chn_44` FLOAT NULL DEFAULT NULL,
  `Chn_45` FLOAT NULL DEFAULT NULL,
  `Chn_46` FLOAT NULL DEFAULT NULL,
  `Chn_47` FLOAT NULL DEFAULT NULL,
  `Chn_48` FLOAT NULL DEFAULT NULL,
  `Chn_49` FLOAT NULL DEFAULT NULL,
  `Chn_50` FLOAT NULL DEFAULT NULL,
  `Average` FLOAT NULL DEFAULT NULL,
  `SD` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`avoid_duplicates`),
  UNIQUE INDEX `evitar_duplicados_UNIQUE` (`avoid_duplicates` ASC) VISIBLE,
  INDEX `idvalv_idx` (`ID_experiment` ASC) VISIBLE,
  CONSTRAINT `idvalv`
    FOREIGN KEY (`ID_experiment`)
    REFERENCES `eoxsense`.`experiments` (`id_experiment`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
